name: CI
on:
    pull_request: null
    push:
        branches:
            - master
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.4', '8.0', '8.1']

        name: Linting - PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: intl
            -   run: composer install --no-progress
            -   run: composer codestyle
            -   run: composer phpstan
            -   run: composer tests

    bundle:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.0', '8.1']
                symfony: ['5.4', '6.2']
                exclude:
                    - php: '8.0'
                      symfony: '6.2'
                    - php: '8.1'
                      symfony: '5.4'

        name: Bundle - SF ${{ matrix.symfony }} - PHP ${{ matrix.php }}
        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: intl
            -   run: composer create-project symfony/skeleton:"${{ matrix.symfony }}.*" .
            -   run: composer require webapp
            -   run: composer install --no-progress
